### ISSUE TITLE
Expected output of test missing

### ISSUE THREAD

**Issue by travc** [ncbi/fcs-gx#8]
You should include the expected output of the test run described in Readme.md in the repo.
`FCS_combo_test.4932.fcs_gx_report.txt`
`FCS_combo_test.4932.taxonomy.rpt`
and preferably the stdout+stderr

I have no clue if the warnings it is giving are expected our not.

**Comment by etvedte** [comment]
Hello,

What errors are you seeing? If you are using the test database, the following warnings are expected since the test db does not contain fungal sequences.

```
Warning: asserted div 'fung:budding yeasts' is not represented in the output!

-----------------------------------------------------------------------------
Warning: Asserted tax-div 'fung:budding yeasts' is well-represented in db, but absent from inferred-primary-divs.
This means that either asserted tax-div is incorrect, or the input is predominantly contamination.
Will trust the asserted div and treat inferred-primary-divs as contaminants.

```

For the full FCS-GX database:
The files should be similar to the files [here](https://github.com/ncbi/fcs/tree/main/examples)
The std logs should look similar to [this](https://github.com/ncbi/fcs/wiki/FCS-GX-quickstart#usage-examples) 

I can update the files for the most recent version, but differences should be minor.

**Comment by travc** [comment]
Ah, the output is in the wiki.  Ok, I missed that.
(Note: I'm running the bioconda install of ncbi-fcs-gx on a decent desktop machine with 128GB RAM)

My output is identical up to...
```
...
Processed 420 queries, 12.5732Mbp in 0.530816s. (23.6864Mbp/s); num-jobs:120

Warning: asserted div 'fung:budding yeasts' is not represented in the output!

Exception ignored in: <_io.BufferedWriter name=6>
Traceback (most recent call last):
  File "/home/travc/miniconda3/fcs-gx/bin/run_gx.py", line 312, in __exit__
    self.wait()
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <_io.BufferedReader name=3>
Traceback (most recent call last):
  File "/home/travc/miniconda3/fcs-gx/bin/run_gx.py", line 312, in __exit__
    self.wait()
OSError: [Errno 9] Bad file descriptor


-----------------------------------------------------------------------------
Warning: Asserted tax-div 'fung:budding yeasts' is well-represented in db, but absent from inferred-primary-divs.
This means that either asserted tax-div is incorrect, or the input is predominantly contamination.
Will trust the asserted div and treat inferred-primary-divs as contaminants.
-----------------------------------------------------------------------------

Species                    : None
Asserted div               : fung:budding yeasts
Inferred primary-divs      : ['prok:CFB group bacteria']
Corrected primary-divs     : ['fung:budding yeasts']
Putative contaminant divs  : ['prok:CFB group bacteria']
Aggregate coverage         : 2%
Minimum contam. coverage   : 59%

-----------------------------------------------------------------------------

fcs_gx_report.txt contamination summary:
----------------------------------------
                                seqs      bases
                               ----- ----------
TOTAL                              2       2000
-----                          ----- ----------
prok:CFB group bacteria            2       2000

-----------------------------------------------------------------------------

fcs_gx_report.txt action summary:
---------------------------------
                                seqs      bases
                               ----- ----------
TOTAL                              2       2000
-----                          ----- ----------
EXCLUDE                            2       2000
```

I was guessing the bad file descriptors were just a cleanup glitch, but apparently not.  
The database was downloaded to `/dev/shm/gxdb` and seems to be there:
```
$ ls -lh /dev/shm/gxdb/
total 4.3G
drwxrwxr-x 2 travc travc  180 Oct 17 10:50 ./
drwxrwxrwt 4 root  root    80 Oct 17 17:11 ../
-rw-rw-r-- 1 travc travc 7.9M Oct 17 10:43 test-only.blast_div.tsv.gz
-rw-rw-r-- 1 travc travc 4.3G Oct 17 10:50 test-only.gxi
-rw-rw-r-- 1 travc travc  68M Oct 17 10:43 test-only.gxs
-rw-rw-r-- 1 travc travc 1.3K Oct 17 10:50 test-only.manifest
-rw-rw-r-- 1 travc travc   56 Oct 17 10:43 test-only.meta.jsonl
-rw-rw-r-- 1 travc travc  22K Oct 17 10:43 test-only.seq_info.tsv.gz
-rw-rw-r-- 1 travc travc 6.0K Oct 17 10:43 test-only.taxa.tsv
```

Any clue?  I could hack the code and try to output some more info about the what those file descriptors are actually referring to, but you might know off the top of your head.

**Comment by etvedte** [comment]
I haven't seen those errors before...the other parts of the log look reasonable.

Did you try this on the full GX database?

**Comment by travc** [comment]
No, this was just the test database.
I'm currently downloading the full gxdb.

**Comment by etvedte** [comment]
Closing the issue. Please re-open if this issue persists.
